### ISSUE TITLE
RE 1.7

### ISSUE THREAD

**Issue by dtmaster79** [GitHub-TC/TranslateCSV#1]
Hi,

wirst du auch eine Übersetzung für RE 1.7 machen? Die Testversion ist ja vor wenigen Stunden heruas gekommen. Das wäre natürlich super.

Viele liebe Grüße

**Comment by GitHub-TC** [comment]
https://empyriononline.com/threads/reforged-eden-1-7-deutsche-%C3%9Cbersetzung.99636/
