### ISSUE TITLE
Unable to translate Chinese (Simplified)

### ISSUE THREAD

**Issue by xiangsj1988** [GitHub-TC/TranslateCSV#2]
When I run
TranslateCSV.exe --csv-input "J:\SteamLibrary\steamapps\workshop\content\383120\2550354956\Extras\PDA\PDA.csv" --deepl-target-language ZH --csv-target-language Chinese (Simplified)
Enter KEY The window will close automatically~

**Comment by GitHub-TC** [comment]
The TranslateCSV.exe is a commandline tool and exit after finished work. Call it from a cmd or powershell box and you will see the output

**Comment by xiangsj1988** [comment]
However, when I ran the translation and entered KEY . He flashed back

**Comment by xiangsj1988** [comment]
[Wrong .txt](https://github.com/GitHub-TC/TranslateCSV/files/8502416/Wrong.txt)

**Comment by GitHub-TC** [comment]
You have to use the API key from DeepL - Details I have described to you in the EGS forum
