### ISSUE TITLE
Reforged Eden 1.8 Atlantis

### ISSUE THREAD

**Issue by jus61** [GitHub-TC/TranslateCSV#3]
Could you integrate Reforged Eden 1.8 Atlantis? 
https://steamcommunity.com/sharedfiles/filedetails/?id=2801133581

**Comment by GitHub-TC** [comment]
Here in the "releases" https://github.com/GitHub-TC/TranslateCSV/releases/tag/RE-1.8v33
https://github.com/GitHub-TC/TranslateCSV/releases/download/RE-1.8v33/Reforged.Eden-Atlantis-Deutsch.1.8v33.zip
